<a href="https://colab.research.google.com/github/xx39xx16/computer_vision/blob/main/forward_propagation_of_neural_networks/01_2_Artificial_Neurons.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
### activation function

In [2]:
#affine function과 activation function이 보통 붙어있는데 그렇지 않은 경우도 있기 때문에 activation function만 만드는 방법도 알아야 함

In [9]:
import tensorflow as tf
from tensorflow.math import exp, maximum
from tensorflow.keras.layers import Activation

x = tf.random.normal(shape = (1,5)) # input setting

# imp. activation function

sigmoid = Activation('sigmoid') # 시그모이드 펑션이 하나 만들어짐
tanh = Activation('tanh')
relu = Activation('relu')

# forward propagation
y_sigmoid_tf = sigmoid(x)
y_tanh_tf = tanh(x)
y_relu_tf = relu(x)

#forward propagation(manual)

y_sigmoid_man = 1 / (1 + exp(-x))
y_tanh_man = (exp(x)  - exp(-x))/ (exp(x) + exp(-x))
y_relu_man = maximum(x,0)

print("x : {}\n{}".format(x.shape, x.numpy()))
print("Sigmoid(Tensorflow) : {}\n{}".format(y_sigmoid_tf.shape, y_sigmoid_tf.numpy()))
print("Sigmoid(manual) : {}\n{}".format(y_sigmoid_man.shape, y_sigmoid_man.numpy()))

print("Tanh(Tensorflow) : {}\n{}".format(y_tanh_tf.shape,y_tanh_tf.numpy()))
print("Tanh(manual) : {}\n{}".format(y_tanh_man.shape,y_tanh_man.numpy()))

print("ReLu(Tensorflow) : {}\n{}".format(y_relu_tf.shape,y_relu_tf.numpy()))
print("ReLu(manual) : {}\n{}".format(y_relu_man.shape,y_relu_man.numpy()))

x : (1, 5)
[[ 1.1003492   1.7455133  -0.06907587 -1.2625792   0.6519807 ]]
Sigmoid(Tensorflow) : (1, 5)
[[0.7503255  0.851386   0.48273787 0.22053023 0.6574567 ]]
Sigmoid(manual) : (1, 5)
[[0.75032556 0.8513861  0.4827379  0.22053023 0.6574567 ]]
Tanh(Tensorflow) : (1, 5)
[[ 0.8006244   0.9408626  -0.06896621 -0.8517736   0.57300186]]
Tanh(manual) : (1, 5)
[[ 0.80062443  0.9408628  -0.06896621 -0.85177356  0.57300186]]
ReLu(Tensorflow) : (1, 5)
[[1.1003492 1.7455133 0.        0.        0.6519807]]
ReLu(manual) : (1, 5)
[[1.1003492 1.7455133 0.        0.        0.6519807]]


In [10]:
 ### activation in dense layer

In [12]:
import tensorflow as tf
from tensorflow.math import exp
from tensorflow.keras.layers import Dense

x = tf.random.normal(shape = (1,5)) # input setting

#imp. artificial neurons

dense_sigmoid = Dense(units = 1, activation = 'sigmoid')
dense_tanh = Dense(units = 1, activation = 'tanh')
dense_relu = Dense(units = 1, activation = 'relu')

# forward propagation
y_sigmoid = dense_sigmoid(x)
y_tanh = dense_tanh(x)
y_relu = dense_relu(x)

print("AN with Sigmoid : {}\n{}".format(y_sigmoid.shape, y_sigmoid.numpy()))
print("AN with Tanh : {}\n{}".format(y_tanh.shape, y_tanh.numpy()))
print("AN with ReLu : {}\n{}".format(y_relu.shape, y_relu.numpy()))

#forward propagation(manual)

print('\n==============\n')
W, B = dense_sigmoid.get_weights()
z = tf.linalg.matmul(x, W) + B
a = 1 / (1 + exp(-z))

print("Activation value (Tensorflow) : {}\n{}".format(y_sigmoid.shape, y_sigmoid.numpy()))
print("Activation value (manual) : {}\n{}".format(a.shape, a.numpy()))

AN with Sigmoid : (1, 1)
[[0.8465323]]
AN with Tanh : (1, 1)
[[-0.81162846]]
AN with ReLu : (1, 1)
[[1.723201]]


In [14]:
### minibatches

In [ ]:
# shapes of dense layers

In [19]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
N,n_feature = 8, 10 #set imput param , 웨이트와 바이어스에 영향 미치지 않음
x = tf.random.normal(shape = (N, n_feature)) #generate minibatch
print(x.shape)

dense = Dense(units =1, activation = 'relu')
y = dense(x) # forward propagation

W,B = dense.get_weights() # get weight/ bias

# print results
print("Shape of x : ", x.shape)
print("Shape of W : ", W.shape)
print("Shape of B : ", B.shape)


(8, 10)
Shape of x :  (8, 10)
Shape of W :  (10, 1)
Shape of B :  (1,)


In [23]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N,n_feature = 8, 10 #set imput param , 웨이트와 바이어스에 영향 미치지 않음
x = tf.random.normal(shape = (N, n_feature)) #generate minibatch

dense = Dense(units =1, activation = 'sigmoid') # import an AN
y_tf = dense(x) # forward propagation(Tensorflow)

W, B = dense.get_weights()
y_man = tf.linalg.matmul(x, W) + B # forward propagation(Manual)
y_man = 1/ (1 + tf.math.exp(-y_man))

#print resuluts

print("Output(Tensorflow): \n", y_tf.numpy())
print("Output(Manual): \n", y_man.numpy())

Output(Tensorflow): 
 [[0.25052088]
 [0.29046327]
 [0.8771275 ]
 [0.6287617 ]
 [0.35221905]
 [0.5464455 ]
 [0.77021074]
 [0.9324029 ]]
Output(Manual): 
 [[0.25052088]
 [0.29046327]
 [0.8771276 ]
 [0.62876165]
 [0.35221905]
 [0.5464455 ]
 [0.77021074]
 [0.9324029 ]]
