<a href="https://colab.research.google.com/github/xx39xx16/computer_vision/blob/main/forward_propagation_of_neural_networks/01_affine_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
### Affine Function

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

x = tf.constant([[10.]]) # input setting (Note : input -> matrix)
print(x)

dense = Dense(units = 1, activation = 'linear') # 하나만 만들거라서. imp.an affine function

y_tf = dense(x)  # forward propagation + params initialization // dense에 w,b 가지고 있는데 이거 z 계산하는 거 의미

W, B = dense.get_weights() ## y_tf랑 순서를 바꾸면 오류가 뜸 // # get weight and bias

#print(W,B)

y_man = tf.linalg.matmul(x,W) + B #forward propagation (manual)



#print results

print('======= Input / Weight / Bias =======')
print("x : {}\n{}\n".format(x.shape, x.numpy()))
print("W : {}\n{}\n".format(W.shape, W))
print("B : {}\n{}\n".format(B.shape, B))

print('======= Output ======')
print("y(Tensorflow): {}\n{}\n".format(y_tf.shape, y_tf.numpy()))
print("y(manual): {}\n{}\n".format(y_man.shape, y_man.numpy()))

tf.Tensor([[10.]], shape=(1, 1), dtype=float32)
======= Input / Weight / Bias =======
x : (1, 1)
[[10.]]

W : (1, 1)
[[-1.7258697]]

B : (1,)
[0.]

======= Output ======
y(Tensorflow): (1, 1)
[[-17.258698]]

y(manual): (1, 1)
[[-17.258698]]



In [ ]:
### parameter initialization


In [ ]:
import tensorflow as tf

from tensorflow.keras.layers import Dense
from tensorflow.keras.initializers import Constant # 내가 원하는 값으로 이니셜라이제이션을 해줄거야


x = tf.constant([[10.]]) # input setting (Note : input -> matrix)

# weight/ bias setting

w,b = tf.constant(10.), tf.constant(20.)
w_init, b_init = Constant(w), Constant(b)

# imp. affine function


dense = Dense(units = 1,
              activation = 'linear',
              kernel_initializer = w_init,
              bias_initializer = b_init)

y_tf = dense(x)
print(y_tf)

W, B = dense.get_weights()

# print results
print("W : {}\n\n".format(W.shape, W))
print("B : {}\n\n".format(B.shape, B))

tf.Tensor([[120.]], shape=(1, 1), dtype=float32)
W : (1, 1)


B : (1,)




In [ ]:
### Affine functions with n Features

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

x = tf.random.uniform(shape = (1,10), minval = 0, maxval=10)

print(x.shape, '\n', x)

dense = Dense(units = 1)

y_tf = dense(x) # 알아서 웨이트랑 바이어스가 몇 갠지 계산해줌

W, B = dense.get_weights()
y_man - tf.linalg.matmul(x, W) + B


#print results

print('======= Input / Weight / Bias =======')
print("x : {}\n{}\n".format(x.shape, x.numpy()))
print("W : {}\n{}\n".format(W.shape, W))
print("B : {}\n{}\n".format(B.shape, B))

print('======= Output ======')
print("y(Tensorflow): {}\n{}\n".format(y_tf.shape, y_tf.numpy()))
print("y(manual): {}\n{}\n".format(y_man.shape, y_man.numpy()))

(1, 10) 
 tf.Tensor(
[[5.1688538  1.7068446  6.5093637  0.25049925 7.5844107  5.0117326
  5.337287   0.73206186 3.6853027  2.2227764 ]], shape=(1, 10), dtype=float32)
======= Input / Weight / Bias =======
x : (1, 10)
[[5.1688538  1.7068446  6.5093637  0.25049925 7.5844107  5.0117326
  5.337287   0.73206186 3.6853027  2.2227764 ]]

W : (10, 1)
[[-0.13652712]
 [ 0.7054443 ]
 [-0.45094952]
 [-0.4066856 ]
 [-0.27654663]
 [ 0.25717688]
 [ 0.220711  ]
 [-0.43945214]
 [-0.25550145]
 [ 0.00905478]]

B : (1,)
[0.]

======= Output ======
y(Tensorflow): (1, 1)
[[-3.4125967]]

y(manual): (1, 1)
[[-17.258698]]

